apiVersion: v1
kind: ConfigMap
metadata:
  name: "developer-hub-appconfig"
  namespace: tools
data:
  developer-hub-appconfig.yaml: |
    enabled:
      argocd: true
      github: true
      githubOrg: false
      gitlab: false
      jenkins: false
      keycloak: false
      kubernetes: true
      ocm: false
      permission: true
      sonarqube: false
      techdocs: true
    organization:
      name: Demo org
    argocd:
      username: ${ARGOCD_USER_ID}
      password: ${ARGOCD_USER_PWD}
      appLocatorMethods:
      - type: 'config'
        instances:
        - name: argocd
          url: https://gitops.sandbox2841.opentlc.com
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
          - url: https://api.workload.sandbox2807.opentlc.com:6443
            name: workload 
            authProvider: oidc
            oidcTokenProvider: okta

          #- url: ${EKS_CLUSTER_URL}
          #  name: ${EKS_CLUSTER_NAME}
          #  authProvider: 'serviceAccount'
          #  caData: ${EKS_CA_DATA}
          #  serviceAccountToken: ${EKS_SA_TOKEN}
    techdocs:
      generator:
        runIn: local
        mkdocs:
          defaultPlugins: ['techdocs-core']
      builder: 'external'
      publisher:
        type: 'awsS3'
        awsS3:
          bucketName: ${TECHDOCS_AWSS3_BUCKET_NAME}
          endPoint: ${TECHDOCS_AWSS3_BUCKET_URL}
          bucketRootPath: '/'
          accountId: ${TECHDOCS_AWS_ACCOUNT_ID}
          credentials:
            accessKeyId: ${AWS_ACCESS_KEY_ID}
            secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION}
          s3ForcePathStyle: true
    signInPage: okta
    auth:
      environment: demo
      session:
        secret: ${AUTH_OKTA_SECRET}
      providers:
        okta:
          demo:
            metadataUrl: ${AUTH_OKTA_DOMAIN}/.well-known/openid-configuration
            clientId: ${AUTH_OKTA_CLIENT_ID}
            clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
            audience: ${AUTH_OKTA_DOMAIN}
            additionalScopes: ${AUTH_OKTA_ADDITIONAL_SCOPES}
        #github:
        #  demo:
        #    clientId: ${GITHUB_APP_CLIENT_ID}
        #    clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    integrations:
      github:
      - host: github.com
        token: ${GITHUB_TOKEN}
        #apps:
        #- appId: ${GITHUB_APP_APP_ID}
        #  clientId: ${GITHUB_APP_CLIENT_ID}
        #  clientSecret: ${GITHUB_APP_CLIENT_SECRET}
        #  webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
        #  webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
        #  privateKey: |
        #    ${GITHUB_APP_PRIVATE_KEY}
    catalog:
      import:
        entityFileName: catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Domain, Template, Group, User]
      locations:
        - type: url
          target: https://github.com/rprakashg-redhat/rhdh-templates/blob/main/all-templates.yaml
        - type: url
          target: https://github.com/rprakashg-redhat/apis/blob/main/all-apis.yaml
        - type: url
          target: https://github.com/rprakashg-redhat/apis/blob/main/acme-corp.yaml
        #- type: github-org
        #  target: https://github.com/${GITHUB_ORG}
        #  rules:
        #    - allow: [User, Group]
      providers:
        github:
          organization: ${GITHUB_ORG}
          catalogPath: '/catalog-info.yaml' # string
          filters:
            branch: 'main' # string
            repository: '.*' # Regex
          schedule:
            frequency:
              minutes: 30
            initialDelay:
              seconds: 15
            timeout:
              minutes: 3