apiVersion: v1
kind: ConfigMap
metadata:
  name: "developer-hub-appconfig"
  namespace: tools
data:
  developer-hub-appconfig.yaml: |
    enabled:
      github: true
      #githubOrg: true
    organization:
      name: Demo org
    kubernetes:
      serviceLocatorMethod: 
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
          - url: ${EKS_CLUSTER_URL}
            name: eks
            serviceAccountToken: ${SA_TOKEN}
            authProvider: 'serviceAccount'
    techdocs:
      generator:
        runIn: local
        mkdocs:
          defaultPlugins: ['techdocs-core']
      builder: 'external'
      publisher:
        type: 'awsS3'
        awsS3:
          bucketName: ${TECHDOCS_AWSS3_BUCKET_NAME}
          endPoint: ${TECHDOCS_AWSS3_BUCKET_URL}
          bucketRootPath: '/'
          accountId: ${TECHDOCS_AWSS3_ACCOUNT_ID}
          credentials:
            accessKeyId: ${AWS_ACCESS_KEY_ID}
            secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
          region: ${AWS_REGION}
          sse: 'aws:kms'
    signInPage: github
    auth:
      environment: demo
      providers:
        github:
          demo:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    integrations:
      github:
      - host: github.com
        token: ${GITHUB_TOKEN}
        apps:
        - appId: ${GITHUB_APP_APP_ID}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: |
            ${GITHUB_APP_PRIVATE_KEY}
    catalog:
      import:
        entityFileName: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Group, User, Resource, Location, Template]
      locations:
        - type: url
          target: https://github.com/rprakashg-redhat/rhdh-templates/blob/main/all-templates.yaml
      providers:
        #githubOrg:
        #  default:
        #    id: development
        #    orgUrl: ${GITHUB_ORG_URL}
        github:
          organization: ${GITHUB_ORG}
          catalogPath: '/catalog-info.yaml' # string
          filters:
            branch: 'main' # string
            repository: '.*' # Regex
          schedule:
            frequency:
              minutes: 30
            initialDelay:
              seconds: 15
            timeout:
              minutes: 3
    permission:
      enabled: true