apiVersion: v1
kind: ConfigMap
metadata:
  name: "developer-hub-appconfig"
  namespace: tools
data:
  developer-hub-appconfig.yaml: |
    signInPage: gitlab
    auth:
      environment: demo
      providers:
        gitlab:
          demo:
            clientId: ${GITLAP_APP_CLIENT_ID}
            clientSecret: ${GITLAB_APP_CLIENT_SECRET}
            audience: https://gitlab.com
            callbackUrl: https://${BASE_URL}/api/auth/gitlab/handler/frame
    
    integrations:
      gitlab:
      - host: gitlab.com
        apps:
        - appId: ${GITLAB_APP_ID}
          clientId: ${GITLAP_APP_CLIENT_ID}
          clientSecret: ${GITLAB_APP_CLIENT_SECRET}
    
    catalog:
      providers:
        gitlab:
          demo:
            host: gitlab.com
            group: rprakashg-redhat
            branch: main
            skipForkedRepos: true
            schedule:
              frequency: { minutes: 30 }
              timeout: { minutes: 3 }
